version: '3.7'

networks:
  cheesetypeapi:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: CheeseTypeDB
    ports:
      - 27016:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - cheesetypeapi
  
  cheesetypeapi:
    image: cheesetypeapi:latest
    depends_on:
      - "mongodb"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"     
    networks:
      - cheesetypeapi

volumes:
  mongodb_data_container: